### Get all characters
GET {{localhost}}:{{port}}/api/asterix/characters

### Get character by name
GET {{localhost}}:{{port}}/api/asterix/characters?name={{name}}

### Get character by id
GET {{localhost}}:{{port}}/api/asterix/character/db626e50-d41a-41b2-a145-1b07968bd236

### Add new character
POST {{localhost}}:{{port}}/api/asterix/character/new
Content-Type: application/json

{
  "name": "Java Student",
  "age": 36,
  "profession": "Warrior"
}

> {%
    var res = response.body
    client.global.set("name", res.name)

 %}

### Update character by id
PUT {{localhost}}:{{port}}/api/asterix/character/db626e50-d41a-41b2-a145-1b07968bd236
Content-Type: application/json

{
  "name": "Junior Java Developer",
  "age": 36,
  "profession": "Warrior"
}

### Remove character by id
DELETE {{localhost}}:{{port}}/api/asterix/character/db626e50-d41a-41b2-a145-1b07968bd236

### Calculate avarege age for one profession
GET {{localhost}}:{{port}}/api/asterix/character/average-age?profession=druid